#!/usr/bin/perl

my $command = "ps";
my $function = "bot_" . $command;

$command_actions{$command}      = \&$function;

sub bot_ps {
        my %bot_message_hash = %{shift @_};
        my $bot_object = $bot_message_hash{bot_object};
        my $fullsender = $bot_message_hash{'from_full'};
        my ($sender) = split(/\@/, "$fullsender");

        my @ARG = @_;
	my @output = undef;
	if(@ARG[0] eq "") { @output = `ps ax` }
	else { @output = "$command options: none" }

	return @output;
}                                                                                                                                                                                                                      
                                                                                                                                                                                                                       
1;                                                                                                                                                                                                                     
                                                                                                                                                                                                                       
                                                                                                                                                                                                                       
                                                                                                                                                                                                                       
                                  
