#! /bin/sh

### BEGIN INIT INFO
# Provides:             skynet-client
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    Skynet Client
### END INIT INFO

set -e

PROGRAM="/etc/skynet-client/skynet-client-bot.pl"
# /etc/init.d/skynet: start and stop the Skynet Client connection daemon

case "$1" in
  start)
        killall -9 skynet-client-bot.pl 2> /dev/null  || true
        echo "Starting Skynet client bot..."
        start-stop-daemon --start -b --quiet --oknodo --exec $PROGRAM
        ;;
  stop)
        echo "Stopping Skynet client bot..."
        killall -9 skynet-client-bot.pl 2> /dev/null
        ;;

  restart)
        echo "Stopping Skynet client bot..."
        killall -9 skynet-client-bot.pl 2> /dev/null
        $0 start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}" || true
        exit 1
esac

exit 0

